// Default include in all modules
#include<vtkNew.h>
#include<vtkObjectBase.h>

// Include objects of this module
#include<vtkArcSource.h>
#include<vtkArrowSource.h>
#include<vtkButtonSource.h>
#include<vtkCapsuleSource.h>
#include<vtkCellTypeSource.h>
#include<vtkConeSource.h>
#include<vtkCubeSource.h>
#include<vtkCylinderSource.h>
#include<vtkDiagonalMatrixSource.h>
#include<vtkDiskSource.h>
#include<vtkEllipseArcSource.h>
#include<vtkEllipticalButtonSource.h>
#include<vtkFrustumSource.h>
#include<vtkGlyphSource2D.h>
#include<vtkGraphToPolyData.h>
#include<vtkHandleSource.h>
#include<vtkHyperTreeGridSource.h>
#include<vtkLineSource.h>
#include<vtkOutlineCornerFilter.h>
#include<vtkOutlineCornerSource.h>
#include<vtkOutlineSource.h>
#include<vtkParametricFunctionSource.h>
#include<vtkPartitionedDataSetCollectionSource.h>
#include<vtkPartitionedDataSetSource.h>
#include<vtkPlaneSource.h>
#include<vtkPlatonicSolidSource.h>
#include<vtkPointHandleSource.h>
#include<vtkPointSource.h>
#include<vtkPolyLineSource.h>
#include<vtkPolyPointSource.h>
#include<vtkProgrammableDataObjectSource.h>
#include<vtkProgrammableSource.h>
#include<vtkRandomHyperTreeGridSource.h>
#include<vtkRectangularButtonSource.h>
#include<vtkRegularPolygonSource.h>
#include<vtkSelectionSource.h>
#include<vtkSphereSource.h>
#include<vtkSuperquadricSource.h>
#include<vtkTessellatedBoxSource.h>
#include<vtkTextSource.h>
#include<vtkTexturedSphereSource.h>
#include<vtkUniformHyperTreeGridSource.h>

// Declare exported functions
extern "C" vtkArcSource * vtkArcSource_new () ;
extern "C" void vtkArcSource_destructor (vtkArcSource * sself) ;
extern "C" void * vtkArcSource_get_ptr (vtkArcSource * sself) ;
extern "C" void vtk_arc_source_set_point_1(vtkArcSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_arc_source_set_point_2(vtkArcSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_arc_source_set_center(vtkArcSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_arc_source_set_normal(vtkArcSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_arc_source_set_polar_vector(vtkArcSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_arc_source_set_angle(vtkArcSource* sself, double _arg);
extern "C" double vtk_arc_source_get_angle_min_value(vtkArcSource* sself);
extern "C" double vtk_arc_source_get_angle_max_value(vtkArcSource* sself);
extern "C" double vtk_arc_source_get_angle(vtkArcSource* sself);
extern "C" void vtk_arc_source_set_resolution(vtkArcSource* sself, int _arg);
extern "C" int vtk_arc_source_get_resolution_min_value(vtkArcSource* sself);
extern "C" int vtk_arc_source_get_resolution_max_value(vtkArcSource* sself);
extern "C" int vtk_arc_source_get_resolution(vtkArcSource* sself);
extern "C" void vtk_arc_source_set_negative(vtkArcSource* sself, bool _arg);
extern "C" bool vtk_arc_source_get_negative(vtkArcSource* sself);
extern "C" void vtk_arc_source_negative_on(vtkArcSource* sself);
extern "C" void vtk_arc_source_negative_off(vtkArcSource* sself);
extern "C" void vtk_arc_source_set_use_normal_and_angle(vtkArcSource* sself, bool _arg);
extern "C" bool vtk_arc_source_get_use_normal_and_angle(vtkArcSource* sself);
extern "C" void vtk_arc_source_use_normal_and_angle_on(vtkArcSource* sself);
extern "C" void vtk_arc_source_use_normal_and_angle_off(vtkArcSource* sself);
extern "C" void vtk_arc_source_set_output_points_precision(vtkArcSource* sself, int _arg);
extern "C" int vtk_arc_source_get_output_points_precision(vtkArcSource* sself);
extern "C" vtkArrowSource * vtkArrowSource_new () ;
extern "C" void vtkArrowSource_destructor (vtkArrowSource * sself) ;
extern "C" void * vtkArrowSource_get_ptr (vtkArrowSource * sself) ;
extern "C" void vtk_arrow_source_set_tip_length(vtkArrowSource* sself, double _arg);
extern "C" double vtk_arrow_source_get_tip_length_min_value(vtkArrowSource* sself);
extern "C" double vtk_arrow_source_get_tip_length_max_value(vtkArrowSource* sself);
extern "C" double vtk_arrow_source_get_tip_length(vtkArrowSource* sself);
extern "C" void vtk_arrow_source_set_tip_radius(vtkArrowSource* sself, double _arg);
extern "C" double vtk_arrow_source_get_tip_radius_min_value(vtkArrowSource* sself);
extern "C" double vtk_arrow_source_get_tip_radius_max_value(vtkArrowSource* sself);
extern "C" double vtk_arrow_source_get_tip_radius(vtkArrowSource* sself);
extern "C" void vtk_arrow_source_set_tip_resolution(vtkArrowSource* sself, int _arg);
extern "C" int vtk_arrow_source_get_tip_resolution_min_value(vtkArrowSource* sself);
extern "C" int vtk_arrow_source_get_tip_resolution_max_value(vtkArrowSource* sself);
extern "C" int vtk_arrow_source_get_tip_resolution(vtkArrowSource* sself);
extern "C" void vtk_arrow_source_set_shaft_radius(vtkArrowSource* sself, double _arg);
extern "C" double vtk_arrow_source_get_shaft_radius_min_value(vtkArrowSource* sself);
extern "C" double vtk_arrow_source_get_shaft_radius_max_value(vtkArrowSource* sself);
extern "C" double vtk_arrow_source_get_shaft_radius(vtkArrowSource* sself);
extern "C" void vtk_arrow_source_set_shaft_resolution(vtkArrowSource* sself, int _arg);
extern "C" int vtk_arrow_source_get_shaft_resolution_min_value(vtkArrowSource* sself);
extern "C" int vtk_arrow_source_get_shaft_resolution_max_value(vtkArrowSource* sself);
extern "C" int vtk_arrow_source_get_shaft_resolution(vtkArrowSource* sself);
extern "C" void vtk_arrow_source_invert_on(vtkArrowSource* sself);
extern "C" void vtk_arrow_source_invert_off(vtkArrowSource* sself);
extern "C" void vtk_arrow_source_set_invert(vtkArrowSource* sself, bool _arg);
extern "C" bool vtk_arrow_source_get_invert(vtkArrowSource* sself);
extern "C" void vtk_arrow_source_set_arrow_origin_to_default(vtkArrowSource* sself);
extern "C" void vtk_arrow_source_set_arrow_origin_to_center(vtkArrowSource* sself);
extern "C" vtkCapsuleSource * vtkCapsuleSource_new () ;
extern "C" void vtkCapsuleSource_destructor (vtkCapsuleSource * sself) ;
extern "C" void * vtkCapsuleSource_get_ptr (vtkCapsuleSource * sself) ;
extern "C" void vtk_capsule_source_set_radius(vtkCapsuleSource* sself, double _arg);
extern "C" double vtk_capsule_source_get_radius_min_value(vtkCapsuleSource* sself);
extern "C" double vtk_capsule_source_get_radius_max_value(vtkCapsuleSource* sself);
extern "C" double vtk_capsule_source_get_radius(vtkCapsuleSource* sself);
extern "C" void vtk_capsule_source_set_center(vtkCapsuleSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_capsule_source_set_cylinder_length(vtkCapsuleSource* sself, double _arg);
extern "C" double vtk_capsule_source_get_cylinder_length_min_value(vtkCapsuleSource* sself);
extern "C" double vtk_capsule_source_get_cylinder_length_max_value(vtkCapsuleSource* sself);
extern "C" double vtk_capsule_source_get_cylinder_length(vtkCapsuleSource* sself);
extern "C" void vtk_capsule_source_set_theta_resolution(vtkCapsuleSource* sself, int _arg);
extern "C" int vtk_capsule_source_get_theta_resolution_min_value(vtkCapsuleSource* sself);
extern "C" int vtk_capsule_source_get_theta_resolution_max_value(vtkCapsuleSource* sself);
extern "C" int vtk_capsule_source_get_theta_resolution(vtkCapsuleSource* sself);
extern "C" void vtk_capsule_source_set_phi_resolution(vtkCapsuleSource* sself, int _arg);
extern "C" int vtk_capsule_source_get_phi_resolution_min_value(vtkCapsuleSource* sself);
extern "C" int vtk_capsule_source_get_phi_resolution_max_value(vtkCapsuleSource* sself);
extern "C" int vtk_capsule_source_get_phi_resolution(vtkCapsuleSource* sself);
extern "C" void vtk_capsule_source_set_lat_long_tessellation(vtkCapsuleSource* sself, int _arg);
extern "C" int vtk_capsule_source_get_lat_long_tessellation(vtkCapsuleSource* sself);
extern "C" void vtk_capsule_source_lat_long_tessellation_on(vtkCapsuleSource* sself);
extern "C" void vtk_capsule_source_lat_long_tessellation_off(vtkCapsuleSource* sself);
extern "C" void vtk_capsule_source_set_output_points_precision(vtkCapsuleSource* sself, int _arg);
extern "C" int vtk_capsule_source_get_output_points_precision(vtkCapsuleSource* sself);
extern "C" vtkCellTypeSource * vtkCellTypeSource_new () ;
extern "C" void vtkCellTypeSource_destructor (vtkCellTypeSource * sself) ;
extern "C" void * vtkCellTypeSource_get_ptr (vtkCellTypeSource * sself) ;
extern "C" void vtk_cell_type_source_set_cell_type(vtkCellTypeSource* sself, int cellType);
extern "C" int vtk_cell_type_source_get_cell_type(vtkCellTypeSource* sself);
extern "C" void vtk_cell_type_source_set_cell_order(vtkCellTypeSource* sself, int _arg);
extern "C" int vtk_cell_type_source_get_cell_order(vtkCellTypeSource* sself);
extern "C" void vtk_cell_type_source_set_complete_quadratic_simplicial_elements(vtkCellTypeSource* sself, bool _arg);
extern "C" bool vtk_cell_type_source_get_complete_quadratic_simplicial_elements(vtkCellTypeSource* sself);
extern "C" void vtk_cell_type_source_complete_quadratic_simplicial_elements_on(vtkCellTypeSource* sself);
extern "C" void vtk_cell_type_source_complete_quadratic_simplicial_elements_off(vtkCellTypeSource* sself);
extern "C" void vtk_cell_type_source_set_polynomial_field_order(vtkCellTypeSource* sself, int _arg);
extern "C" int vtk_cell_type_source_get_polynomial_field_order_min_value(vtkCellTypeSource* sself);
extern "C" int vtk_cell_type_source_get_polynomial_field_order_max_value(vtkCellTypeSource* sself);
extern "C" int vtk_cell_type_source_get_polynomial_field_order(vtkCellTypeSource* sself);
extern "C" int vtk_cell_type_source_get_cell_dimension(vtkCellTypeSource* sself);
extern "C" void vtk_cell_type_source_set_output_precision(vtkCellTypeSource* sself, int _arg);
extern "C" int vtk_cell_type_source_get_output_precision_min_value(vtkCellTypeSource* sself);
extern "C" int vtk_cell_type_source_get_output_precision_max_value(vtkCellTypeSource* sself);
extern "C" int vtk_cell_type_source_get_output_precision(vtkCellTypeSource* sself);
extern "C" vtkConeSource * vtkConeSource_new () ;
extern "C" void vtkConeSource_destructor (vtkConeSource * sself) ;
extern "C" void * vtkConeSource_get_ptr (vtkConeSource * sself) ;
extern "C" void vtk_cone_source_set_height(vtkConeSource* sself, double _arg);
extern "C" double vtk_cone_source_get_height_min_value(vtkConeSource* sself);
extern "C" double vtk_cone_source_get_height_max_value(vtkConeSource* sself);
extern "C" double vtk_cone_source_get_height(vtkConeSource* sself);
extern "C" void vtk_cone_source_set_radius(vtkConeSource* sself, double _arg);
extern "C" double vtk_cone_source_get_radius_min_value(vtkConeSource* sself);
extern "C" double vtk_cone_source_get_radius_max_value(vtkConeSource* sself);
extern "C" double vtk_cone_source_get_radius(vtkConeSource* sself);
extern "C" void vtk_cone_source_set_resolution(vtkConeSource* sself, int _arg);
extern "C" int vtk_cone_source_get_resolution_min_value(vtkConeSource* sself);
extern "C" int vtk_cone_source_get_resolution_max_value(vtkConeSource* sself);
extern "C" int vtk_cone_source_get_resolution(vtkConeSource* sself);
extern "C" void vtk_cone_source_set_center(vtkConeSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_cone_source_set_direction(vtkConeSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_cone_source_set_angle(vtkConeSource* sself, double angle);
extern "C" double vtk_cone_source_get_angle(vtkConeSource* sself);
extern "C" void vtk_cone_source_set_capping(vtkConeSource* sself, int _arg);
extern "C" int vtk_cone_source_get_capping(vtkConeSource* sself);
extern "C" void vtk_cone_source_capping_on(vtkConeSource* sself);
extern "C" void vtk_cone_source_capping_off(vtkConeSource* sself);
extern "C" void vtk_cone_source_set_output_points_precision(vtkConeSource* sself, int _arg);
extern "C" int vtk_cone_source_get_output_points_precision(vtkConeSource* sself);
extern "C" vtkCubeSource * vtkCubeSource_new () ;
extern "C" void vtkCubeSource_destructor (vtkCubeSource * sself) ;
extern "C" void * vtkCubeSource_get_ptr (vtkCubeSource * sself) ;
extern "C" void vtk_cube_source_set_x_length(vtkCubeSource* sself, double _arg);
extern "C" double vtk_cube_source_get_x_length_min_value(vtkCubeSource* sself);
extern "C" double vtk_cube_source_get_x_length_max_value(vtkCubeSource* sself);
extern "C" double vtk_cube_source_get_x_length(vtkCubeSource* sself);
extern "C" void vtk_cube_source_set_y_length(vtkCubeSource* sself, double _arg);
extern "C" double vtk_cube_source_get_y_length_min_value(vtkCubeSource* sself);
extern "C" double vtk_cube_source_get_y_length_max_value(vtkCubeSource* sself);
extern "C" double vtk_cube_source_get_y_length(vtkCubeSource* sself);
extern "C" void vtk_cube_source_set_z_length(vtkCubeSource* sself, double _arg);
extern "C" double vtk_cube_source_get_z_length_min_value(vtkCubeSource* sself);
extern "C" double vtk_cube_source_get_z_length_max_value(vtkCubeSource* sself);
extern "C" double vtk_cube_source_get_z_length(vtkCubeSource* sself);
extern "C" void vtk_cube_source_set_center(vtkCubeSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_cube_source_set_bounds(vtkCubeSource* sself, double xMin, double xMax, double yMin, double yMax, double zMin, double zMax);
extern "C" void vtk_cube_source_set_output_points_precision(vtkCubeSource* sself, int _arg);
extern "C" int vtk_cube_source_get_output_points_precision(vtkCubeSource* sself);
extern "C" vtkCylinderSource * vtkCylinderSource_new () ;
extern "C" void vtkCylinderSource_destructor (vtkCylinderSource * sself) ;
extern "C" void * vtkCylinderSource_get_ptr (vtkCylinderSource * sself) ;
extern "C" void vtk_cylinder_source_set_height(vtkCylinderSource* sself, double _arg);
extern "C" double vtk_cylinder_source_get_height_min_value(vtkCylinderSource* sself);
extern "C" double vtk_cylinder_source_get_height_max_value(vtkCylinderSource* sself);
extern "C" double vtk_cylinder_source_get_height(vtkCylinderSource* sself);
extern "C" void vtk_cylinder_source_set_radius(vtkCylinderSource* sself, double _arg);
extern "C" double vtk_cylinder_source_get_radius_min_value(vtkCylinderSource* sself);
extern "C" double vtk_cylinder_source_get_radius_max_value(vtkCylinderSource* sself);
extern "C" double vtk_cylinder_source_get_radius(vtkCylinderSource* sself);
extern "C" void vtk_cylinder_source_set_center(vtkCylinderSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_cylinder_source_set_resolution(vtkCylinderSource* sself, int _arg);
extern "C" int vtk_cylinder_source_get_resolution_min_value(vtkCylinderSource* sself);
extern "C" int vtk_cylinder_source_get_resolution_max_value(vtkCylinderSource* sself);
extern "C" int vtk_cylinder_source_get_resolution(vtkCylinderSource* sself);
extern "C" void vtk_cylinder_source_set_capping(vtkCylinderSource* sself, int _arg);
extern "C" int vtk_cylinder_source_get_capping(vtkCylinderSource* sself);
extern "C" void vtk_cylinder_source_capping_on(vtkCylinderSource* sself);
extern "C" void vtk_cylinder_source_capping_off(vtkCylinderSource* sself);
extern "C" void vtk_cylinder_source_set_output_points_precision(vtkCylinderSource* sself, int _arg);
extern "C" int vtk_cylinder_source_get_output_points_precision(vtkCylinderSource* sself);
extern "C" vtkDiagonalMatrixSource * vtkDiagonalMatrixSource_new () ;
extern "C" void vtkDiagonalMatrixSource_destructor (vtkDiagonalMatrixSource * sself) ;
extern "C" void * vtkDiagonalMatrixSource_get_ptr (vtkDiagonalMatrixSource * sself) ;
extern "C" int vtk_diagonal_matrix_source_get_array_type(vtkDiagonalMatrixSource* sself);
extern "C" void vtk_diagonal_matrix_source_set_array_type(vtkDiagonalMatrixSource* sself, int _arg);
extern "C" long long vtk_diagonal_matrix_source_get_extents(vtkDiagonalMatrixSource* sself);
extern "C" void vtk_diagonal_matrix_source_set_extents(vtkDiagonalMatrixSource* sself, long long _arg);
extern "C" double vtk_diagonal_matrix_source_get_diagonal(vtkDiagonalMatrixSource* sself);
extern "C" void vtk_diagonal_matrix_source_set_diagonal(vtkDiagonalMatrixSource* sself, double _arg);
extern "C" double vtk_diagonal_matrix_source_get_super_diagonal(vtkDiagonalMatrixSource* sself);
extern "C" void vtk_diagonal_matrix_source_set_super_diagonal(vtkDiagonalMatrixSource* sself, double _arg);
extern "C" double vtk_diagonal_matrix_source_get_sub_diagonal(vtkDiagonalMatrixSource* sself);
extern "C" void vtk_diagonal_matrix_source_set_sub_diagonal(vtkDiagonalMatrixSource* sself, double _arg);
extern "C" void vtk_diagonal_matrix_source_set_row_label(vtkDiagonalMatrixSource* sself, const char* _arg);
extern "C" void vtk_diagonal_matrix_source_set_column_label(vtkDiagonalMatrixSource* sself, const char* _arg);
extern "C" vtkDiskSource * vtkDiskSource_new () ;
extern "C" void vtkDiskSource_destructor (vtkDiskSource * sself) ;
extern "C" void * vtkDiskSource_get_ptr (vtkDiskSource * sself) ;
extern "C" void vtk_disk_source_set_inner_radius(vtkDiskSource* sself, double _arg);
extern "C" double vtk_disk_source_get_inner_radius_min_value(vtkDiskSource* sself);
extern "C" double vtk_disk_source_get_inner_radius_max_value(vtkDiskSource* sself);
extern "C" double vtk_disk_source_get_inner_radius(vtkDiskSource* sself);
extern "C" void vtk_disk_source_set_outer_radius(vtkDiskSource* sself, double _arg);
extern "C" double vtk_disk_source_get_outer_radius_min_value(vtkDiskSource* sself);
extern "C" double vtk_disk_source_get_outer_radius_max_value(vtkDiskSource* sself);
extern "C" double vtk_disk_source_get_outer_radius(vtkDiskSource* sself);
extern "C" void vtk_disk_source_set_radial_resolution(vtkDiskSource* sself, int _arg);
extern "C" int vtk_disk_source_get_radial_resolution_min_value(vtkDiskSource* sself);
extern "C" int vtk_disk_source_get_radial_resolution_max_value(vtkDiskSource* sself);
extern "C" int vtk_disk_source_get_radial_resolution(vtkDiskSource* sself);
extern "C" void vtk_disk_source_set_circumferential_resolution(vtkDiskSource* sself, int _arg);
extern "C" int vtk_disk_source_get_circumferential_resolution_min_value(vtkDiskSource* sself);
extern "C" int vtk_disk_source_get_circumferential_resolution_max_value(vtkDiskSource* sself);
extern "C" int vtk_disk_source_get_circumferential_resolution(vtkDiskSource* sself);
extern "C" void vtk_disk_source_set_output_points_precision(vtkDiskSource* sself, int _arg);
extern "C" int vtk_disk_source_get_output_points_precision(vtkDiskSource* sself);
extern "C" vtkEllipseArcSource * vtkEllipseArcSource_new () ;
extern "C" void vtkEllipseArcSource_destructor (vtkEllipseArcSource * sself) ;
extern "C" void * vtkEllipseArcSource_get_ptr (vtkEllipseArcSource * sself) ;
extern "C" void vtk_ellipse_arc_source_set_center(vtkEllipseArcSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_ellipse_arc_source_set_normal(vtkEllipseArcSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_ellipse_arc_source_set_major_radius_vector(vtkEllipseArcSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_ellipse_arc_source_set_start_angle(vtkEllipseArcSource* sself, double _arg);
extern "C" double vtk_ellipse_arc_source_get_start_angle_min_value(vtkEllipseArcSource* sself);
extern "C" double vtk_ellipse_arc_source_get_start_angle_max_value(vtkEllipseArcSource* sself);
extern "C" double vtk_ellipse_arc_source_get_start_angle(vtkEllipseArcSource* sself);
extern "C" void vtk_ellipse_arc_source_set_segment_angle(vtkEllipseArcSource* sself, double _arg);
extern "C" double vtk_ellipse_arc_source_get_segment_angle_min_value(vtkEllipseArcSource* sself);
extern "C" double vtk_ellipse_arc_source_get_segment_angle_max_value(vtkEllipseArcSource* sself);
extern "C" double vtk_ellipse_arc_source_get_segment_angle(vtkEllipseArcSource* sself);
extern "C" void vtk_ellipse_arc_source_set_resolution(vtkEllipseArcSource* sself, int _arg);
extern "C" int vtk_ellipse_arc_source_get_resolution_min_value(vtkEllipseArcSource* sself);
extern "C" int vtk_ellipse_arc_source_get_resolution_max_value(vtkEllipseArcSource* sself);
extern "C" int vtk_ellipse_arc_source_get_resolution(vtkEllipseArcSource* sself);
extern "C" void vtk_ellipse_arc_source_set_close(vtkEllipseArcSource* sself, bool _arg);
extern "C" bool vtk_ellipse_arc_source_get_close(vtkEllipseArcSource* sself);
extern "C" void vtk_ellipse_arc_source_close_on(vtkEllipseArcSource* sself);
extern "C" void vtk_ellipse_arc_source_close_off(vtkEllipseArcSource* sself);
extern "C" void vtk_ellipse_arc_source_set_output_points_precision(vtkEllipseArcSource* sself, int _arg);
extern "C" int vtk_ellipse_arc_source_get_output_points_precision(vtkEllipseArcSource* sself);
extern "C" void vtk_ellipse_arc_source_set_ratio(vtkEllipseArcSource* sself, double _arg);
extern "C" double vtk_ellipse_arc_source_get_ratio_min_value(vtkEllipseArcSource* sself);
extern "C" double vtk_ellipse_arc_source_get_ratio_max_value(vtkEllipseArcSource* sself);
extern "C" double vtk_ellipse_arc_source_get_ratio(vtkEllipseArcSource* sself);
extern "C" vtkEllipticalButtonSource * vtkEllipticalButtonSource_new () ;
extern "C" void vtkEllipticalButtonSource_destructor (vtkEllipticalButtonSource * sself) ;
extern "C" void * vtkEllipticalButtonSource_get_ptr (vtkEllipticalButtonSource * sself) ;
extern "C" void vtk_elliptical_button_source_set_width(vtkEllipticalButtonSource* sself, double _arg);
extern "C" double vtk_elliptical_button_source_get_width_min_value(vtkEllipticalButtonSource* sself);
extern "C" double vtk_elliptical_button_source_get_width_max_value(vtkEllipticalButtonSource* sself);
extern "C" double vtk_elliptical_button_source_get_width(vtkEllipticalButtonSource* sself);
extern "C" void vtk_elliptical_button_source_set_height(vtkEllipticalButtonSource* sself, double _arg);
extern "C" double vtk_elliptical_button_source_get_height_min_value(vtkEllipticalButtonSource* sself);
extern "C" double vtk_elliptical_button_source_get_height_max_value(vtkEllipticalButtonSource* sself);
extern "C" double vtk_elliptical_button_source_get_height(vtkEllipticalButtonSource* sself);
extern "C" void vtk_elliptical_button_source_set_depth(vtkEllipticalButtonSource* sself, double _arg);
extern "C" double vtk_elliptical_button_source_get_depth_min_value(vtkEllipticalButtonSource* sself);
extern "C" double vtk_elliptical_button_source_get_depth_max_value(vtkEllipticalButtonSource* sself);
extern "C" double vtk_elliptical_button_source_get_depth(vtkEllipticalButtonSource* sself);
extern "C" void vtk_elliptical_button_source_set_circumferential_resolution(vtkEllipticalButtonSource* sself, int _arg);
extern "C" int vtk_elliptical_button_source_get_circumferential_resolution_min_value(vtkEllipticalButtonSource* sself);
extern "C" int vtk_elliptical_button_source_get_circumferential_resolution_max_value(vtkEllipticalButtonSource* sself);
extern "C" int vtk_elliptical_button_source_get_circumferential_resolution(vtkEllipticalButtonSource* sself);
extern "C" void vtk_elliptical_button_source_set_texture_resolution(vtkEllipticalButtonSource* sself, int _arg);
extern "C" int vtk_elliptical_button_source_get_texture_resolution_min_value(vtkEllipticalButtonSource* sself);
extern "C" int vtk_elliptical_button_source_get_texture_resolution_max_value(vtkEllipticalButtonSource* sself);
extern "C" int vtk_elliptical_button_source_get_texture_resolution(vtkEllipticalButtonSource* sself);
extern "C" void vtk_elliptical_button_source_set_shoulder_resolution(vtkEllipticalButtonSource* sself, int _arg);
extern "C" int vtk_elliptical_button_source_get_shoulder_resolution_min_value(vtkEllipticalButtonSource* sself);
extern "C" int vtk_elliptical_button_source_get_shoulder_resolution_max_value(vtkEllipticalButtonSource* sself);
extern "C" int vtk_elliptical_button_source_get_shoulder_resolution(vtkEllipticalButtonSource* sself);
extern "C" void vtk_elliptical_button_source_set_radial_ratio(vtkEllipticalButtonSource* sself, double _arg);
extern "C" double vtk_elliptical_button_source_get_radial_ratio_min_value(vtkEllipticalButtonSource* sself);
extern "C" double vtk_elliptical_button_source_get_radial_ratio_max_value(vtkEllipticalButtonSource* sself);
extern "C" double vtk_elliptical_button_source_get_radial_ratio(vtkEllipticalButtonSource* sself);
extern "C" void vtk_elliptical_button_source_set_output_points_precision(vtkEllipticalButtonSource* sself, int _arg);
extern "C" int vtk_elliptical_button_source_get_output_points_precision(vtkEllipticalButtonSource* sself);
extern "C" vtkFrustumSource * vtkFrustumSource_new () ;
extern "C" void vtkFrustumSource_destructor (vtkFrustumSource * sself) ;
extern "C" void * vtkFrustumSource_get_ptr (vtkFrustumSource * sself) ;
extern "C" bool vtk_frustum_source_get_show_lines(vtkFrustumSource* sself);
extern "C" void vtk_frustum_source_set_show_lines(vtkFrustumSource* sself, bool _arg);
extern "C" void vtk_frustum_source_show_lines_on(vtkFrustumSource* sself);
extern "C" void vtk_frustum_source_show_lines_off(vtkFrustumSource* sself);
extern "C" double vtk_frustum_source_get_lines_length(vtkFrustumSource* sself);
extern "C" void vtk_frustum_source_set_lines_length(vtkFrustumSource* sself, double _arg);
extern "C" unsigned long vtk_frustum_source_get_m_time(vtkFrustumSource* sself);
extern "C" void vtk_frustum_source_set_output_points_precision(vtkFrustumSource* sself, int _arg);
extern "C" int vtk_frustum_source_get_output_points_precision(vtkFrustumSource* sself);
extern "C" vtkGlyphSource2D * vtkGlyphSource2D_new () ;
extern "C" void vtkGlyphSource2D_destructor (vtkGlyphSource2D * sself) ;
extern "C" void * vtkGlyphSource2D_get_ptr (vtkGlyphSource2D * sself) ;
extern "C" void vtk_glyph_source_2_d_set_center(vtkGlyphSource2D* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_glyph_source_2_d_set_scale(vtkGlyphSource2D* sself, double _arg);
extern "C" double vtk_glyph_source_2_d_get_scale_min_value(vtkGlyphSource2D* sself);
extern "C" double vtk_glyph_source_2_d_get_scale_max_value(vtkGlyphSource2D* sself);
extern "C" double vtk_glyph_source_2_d_get_scale(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_scale_2(vtkGlyphSource2D* sself, double _arg);
extern "C" double vtk_glyph_source_2_d_get_scale_2_min_value(vtkGlyphSource2D* sself);
extern "C" double vtk_glyph_source_2_d_get_scale_2_max_value(vtkGlyphSource2D* sself);
extern "C" double vtk_glyph_source_2_d_get_scale_2(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_color(vtkGlyphSource2D* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_glyph_source_2_d_set_filled(vtkGlyphSource2D* sself, int _arg);
extern "C" int vtk_glyph_source_2_d_get_filled(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_filled_on(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_filled_off(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_dash(vtkGlyphSource2D* sself, int _arg);
extern "C" int vtk_glyph_source_2_d_get_dash(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_dash_on(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_dash_off(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_cross(vtkGlyphSource2D* sself, int _arg);
extern "C" int vtk_glyph_source_2_d_get_cross(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_cross_on(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_cross_off(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_rotation_angle(vtkGlyphSource2D* sself, double _arg);
extern "C" double vtk_glyph_source_2_d_get_rotation_angle(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_resolution(vtkGlyphSource2D* sself, int _arg);
extern "C" int vtk_glyph_source_2_d_get_resolution_min_value(vtkGlyphSource2D* sself);
extern "C" int vtk_glyph_source_2_d_get_resolution_max_value(vtkGlyphSource2D* sself);
extern "C" int vtk_glyph_source_2_d_get_resolution(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type(vtkGlyphSource2D* sself, int _arg);
extern "C" int vtk_glyph_source_2_d_get_glyph_type_min_value(vtkGlyphSource2D* sself);
extern "C" int vtk_glyph_source_2_d_get_glyph_type_max_value(vtkGlyphSource2D* sself);
extern "C" int vtk_glyph_source_2_d_get_glyph_type(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_none(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_vertex(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_dash(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_cross(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_thick_cross(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_triangle(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_square(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_circle(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_diamond(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_arrow(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_thick_arrow(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_hooked_arrow(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_glyph_type_to_edge_arrow(vtkGlyphSource2D* sself);
extern "C" void vtk_glyph_source_2_d_set_output_points_precision(vtkGlyphSource2D* sself, int _arg);
extern "C" int vtk_glyph_source_2_d_get_output_points_precision(vtkGlyphSource2D* sself);
extern "C" vtkGraphToPolyData * vtkGraphToPolyData_new () ;
extern "C" void vtkGraphToPolyData_destructor (vtkGraphToPolyData * sself) ;
extern "C" void * vtkGraphToPolyData_get_ptr (vtkGraphToPolyData * sself) ;
extern "C" void vtk_graph_to_poly_data_set_edge_glyph_output(vtkGraphToPolyData* sself, bool _arg);
extern "C" bool vtk_graph_to_poly_data_get_edge_glyph_output(vtkGraphToPolyData* sself);
extern "C" void vtk_graph_to_poly_data_edge_glyph_output_on(vtkGraphToPolyData* sself);
extern "C" void vtk_graph_to_poly_data_edge_glyph_output_off(vtkGraphToPolyData* sself);
extern "C" void vtk_graph_to_poly_data_set_edge_glyph_position(vtkGraphToPolyData* sself, double _arg);
extern "C" double vtk_graph_to_poly_data_get_edge_glyph_position(vtkGraphToPolyData* sself);
extern "C" vtkHyperTreeGridSource * vtkHyperTreeGridSource_new () ;
extern "C" void vtkHyperTreeGridSource_destructor (vtkHyperTreeGridSource * sself) ;
extern "C" void * vtkHyperTreeGridSource_get_ptr (vtkHyperTreeGridSource * sself) ;
extern "C" unsigned int vtk_hyper_tree_grid_source_get_maximum_level(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_set_maximum_level(vtkHyperTreeGridSource* sself, unsigned int levels);
extern "C" unsigned int vtk_hyper_tree_grid_source_get_max_depth(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_set_max_depth(vtkHyperTreeGridSource* sself, unsigned int levels);
extern "C" void vtk_hyper_tree_grid_source_set_origin(vtkHyperTreeGridSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_hyper_tree_grid_source_set_grid_scale(vtkHyperTreeGridSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_hyper_tree_grid_source_set_transposed_root_indexing(vtkHyperTreeGridSource* sself, bool _arg);
extern "C" bool vtk_hyper_tree_grid_source_get_transposed_root_indexing(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_set_indexing_mode_to_kji(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_set_indexing_mode_to_ijk(vtkHyperTreeGridSource* sself);
extern "C" unsigned int vtk_hyper_tree_grid_source_get_orientation(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_set_branch_factor(vtkHyperTreeGridSource* sself, unsigned int _arg);
extern "C" unsigned int vtk_hyper_tree_grid_source_get_branch_factor_min_value(vtkHyperTreeGridSource* sself);
extern "C" unsigned int vtk_hyper_tree_grid_source_get_branch_factor_max_value(vtkHyperTreeGridSource* sself);
extern "C" unsigned int vtk_hyper_tree_grid_source_get_branch_factor(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_set_use_descriptor(vtkHyperTreeGridSource* sself, bool _arg);
extern "C" bool vtk_hyper_tree_grid_source_get_use_descriptor(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_use_descriptor_on(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_use_descriptor_off(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_set_use_mask(vtkHyperTreeGridSource* sself, bool _arg);
extern "C" bool vtk_hyper_tree_grid_source_get_use_mask(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_use_mask_on(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_use_mask_off(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_set_generate_interface_fields(vtkHyperTreeGridSource* sself, bool _arg);
extern "C" bool vtk_hyper_tree_grid_source_get_generate_interface_fields(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_generate_interface_fields_on(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_generate_interface_fields_off(vtkHyperTreeGridSource* sself);
extern "C" void vtk_hyper_tree_grid_source_set_descriptor(vtkHyperTreeGridSource* sself, const char* _arg);
extern "C" void vtk_hyper_tree_grid_source_set_mask(vtkHyperTreeGridSource* sself, const char* _arg);
extern "C" unsigned long vtk_hyper_tree_grid_source_get_m_time(vtkHyperTreeGridSource* sself);
extern "C" vtkLineSource * vtkLineSource_new () ;
extern "C" void vtkLineSource_destructor (vtkLineSource * sself) ;
extern "C" void * vtkLineSource_get_ptr (vtkLineSource * sself) ;
extern "C" void vtk_line_source_set_point_1(vtkLineSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_line_source_set_point_2(vtkLineSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_line_source_set_use_regular_refinement(vtkLineSource* sself, bool _arg);
extern "C" bool vtk_line_source_get_use_regular_refinement(vtkLineSource* sself);
extern "C" void vtk_line_source_use_regular_refinement_on(vtkLineSource* sself);
extern "C" void vtk_line_source_use_regular_refinement_off(vtkLineSource* sself);
extern "C" void vtk_line_source_set_resolution(vtkLineSource* sself, int _arg);
extern "C" int vtk_line_source_get_resolution_min_value(vtkLineSource* sself);
extern "C" int vtk_line_source_get_resolution_max_value(vtkLineSource* sself);
extern "C" int vtk_line_source_get_resolution(vtkLineSource* sself);
extern "C" void vtk_line_source_set_number_of_refinement_ratios(vtkLineSource* sself, int p0);
extern "C" void vtk_line_source_set_refinement_ratio(vtkLineSource* sself, int index, double value);
extern "C" int vtk_line_source_get_number_of_refinement_ratios(vtkLineSource* sself);
extern "C" double vtk_line_source_get_refinement_ratio(vtkLineSource* sself, int index);
extern "C" void vtk_line_source_set_output_points_precision(vtkLineSource* sself, int _arg);
extern "C" int vtk_line_source_get_output_points_precision(vtkLineSource* sself);
extern "C" vtkOutlineCornerFilter * vtkOutlineCornerFilter_new () ;
extern "C" void vtkOutlineCornerFilter_destructor (vtkOutlineCornerFilter * sself) ;
extern "C" void * vtkOutlineCornerFilter_get_ptr (vtkOutlineCornerFilter * sself) ;
extern "C" void vtk_outline_corner_filter_set_corner_factor(vtkOutlineCornerFilter* sself, double _arg);
extern "C" double vtk_outline_corner_filter_get_corner_factor_min_value(vtkOutlineCornerFilter* sself);
extern "C" double vtk_outline_corner_filter_get_corner_factor_max_value(vtkOutlineCornerFilter* sself);
extern "C" double vtk_outline_corner_filter_get_corner_factor(vtkOutlineCornerFilter* sself);
extern "C" vtkOutlineCornerSource * vtkOutlineCornerSource_new () ;
extern "C" void vtkOutlineCornerSource_destructor (vtkOutlineCornerSource * sself) ;
extern "C" void * vtkOutlineCornerSource_get_ptr (vtkOutlineCornerSource * sself) ;
extern "C" void vtk_outline_corner_source_set_corner_factor(vtkOutlineCornerSource* sself, double _arg);
extern "C" double vtk_outline_corner_source_get_corner_factor_min_value(vtkOutlineCornerSource* sself);
extern "C" double vtk_outline_corner_source_get_corner_factor_max_value(vtkOutlineCornerSource* sself);
extern "C" double vtk_outline_corner_source_get_corner_factor(vtkOutlineCornerSource* sself);
extern "C" vtkOutlineSource * vtkOutlineSource_new () ;
extern "C" void vtkOutlineSource_destructor (vtkOutlineSource * sself) ;
extern "C" void * vtkOutlineSource_get_ptr (vtkOutlineSource * sself) ;
extern "C" void vtk_outline_source_set_box_type(vtkOutlineSource* sself, int _arg);
extern "C" int vtk_outline_source_get_box_type(vtkOutlineSource* sself);
extern "C" void vtk_outline_source_set_box_type_to_axis_aligned(vtkOutlineSource* sself);
extern "C" void vtk_outline_source_set_box_type_to_oriented(vtkOutlineSource* sself);
extern "C" void vtk_outline_source_set_bounds(vtkOutlineSource* sself, double _arg1, double _arg2, double _arg3, double _arg4, double _arg5, double _arg6);
extern "C" void vtk_outline_source_set_generate_faces(vtkOutlineSource* sself, int _arg);
extern "C" void vtk_outline_source_generate_faces_on(vtkOutlineSource* sself);
extern "C" void vtk_outline_source_generate_faces_off(vtkOutlineSource* sself);
extern "C" int vtk_outline_source_get_generate_faces(vtkOutlineSource* sself);
extern "C" void vtk_outline_source_set_output_points_precision(vtkOutlineSource* sself, int _arg);
extern "C" int vtk_outline_source_get_output_points_precision(vtkOutlineSource* sself);
extern "C" vtkParametricFunctionSource * vtkParametricFunctionSource_new () ;
extern "C" void vtkParametricFunctionSource_destructor (vtkParametricFunctionSource * sself) ;
extern "C" void * vtkParametricFunctionSource_get_ptr (vtkParametricFunctionSource * sself) ;
extern "C" void vtk_parametric_function_source_set_u_resolution(vtkParametricFunctionSource* sself, int _arg);
extern "C" int vtk_parametric_function_source_get_u_resolution_min_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_u_resolution_max_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_u_resolution(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_v_resolution(vtkParametricFunctionSource* sself, int _arg);
extern "C" int vtk_parametric_function_source_get_v_resolution_min_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_v_resolution_max_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_v_resolution(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_w_resolution(vtkParametricFunctionSource* sself, int _arg);
extern "C" int vtk_parametric_function_source_get_w_resolution_min_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_w_resolution_max_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_w_resolution(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_generate_texture_coordinates_on(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_generate_texture_coordinates_off(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_generate_texture_coordinates(vtkParametricFunctionSource* sself, int _arg);
extern "C" int vtk_parametric_function_source_get_generate_texture_coordinates_min_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_generate_texture_coordinates_max_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_generate_texture_coordinates(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_generate_normals_on(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_generate_normals_off(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_generate_normals(vtkParametricFunctionSource* sself, int _arg);
extern "C" int vtk_parametric_function_source_get_generate_normals_min_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_generate_normals_max_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_generate_normals(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode(vtkParametricFunctionSource* sself, int _arg);
extern "C" int vtk_parametric_function_source_get_scalar_mode_min_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_scalar_mode_max_value(vtkParametricFunctionSource* sself);
extern "C" int vtk_parametric_function_source_get_scalar_mode(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_none(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_u(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_v(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_u_0(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_v_0(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_u_0_v_0(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_modulus(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_phase(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_quadrant(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_x(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_y(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_z(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_distance(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_scalar_mode_to_function_defined(vtkParametricFunctionSource* sself);
extern "C" unsigned long vtk_parametric_function_source_get_m_time(vtkParametricFunctionSource* sself);
extern "C" void vtk_parametric_function_source_set_output_points_precision(vtkParametricFunctionSource* sself, int _arg);
extern "C" int vtk_parametric_function_source_get_output_points_precision(vtkParametricFunctionSource* sself);
extern "C" vtkPartitionedDataSetCollectionSource * vtkPartitionedDataSetCollectionSource_new () ;
extern "C" void vtkPartitionedDataSetCollectionSource_destructor (vtkPartitionedDataSetCollectionSource * sself) ;
extern "C" void * vtkPartitionedDataSetCollectionSource_get_ptr (vtkPartitionedDataSetCollectionSource * sself) ;
extern "C" void vtk_partitioned_data_set_collection_source_set_number_of_shapes(vtkPartitionedDataSetCollectionSource* sself, int _arg);
extern "C" int vtk_partitioned_data_set_collection_source_get_number_of_shapes_min_value(vtkPartitionedDataSetCollectionSource* sself);
extern "C" int vtk_partitioned_data_set_collection_source_get_number_of_shapes_max_value(vtkPartitionedDataSetCollectionSource* sself);
extern "C" int vtk_partitioned_data_set_collection_source_get_number_of_shapes(vtkPartitionedDataSetCollectionSource* sself);
extern "C" vtkPartitionedDataSetSource * vtkPartitionedDataSetSource_new () ;
extern "C" void vtkPartitionedDataSetSource_destructor (vtkPartitionedDataSetSource * sself) ;
extern "C" void * vtkPartitionedDataSetSource_get_ptr (vtkPartitionedDataSetSource * sself) ;
extern "C" void vtk_partitioned_data_set_source_enable_rank(vtkPartitionedDataSetSource* sself, int rank);
extern "C" void vtk_partitioned_data_set_source_enable_all_ranks(vtkPartitionedDataSetSource* sself);
extern "C" void vtk_partitioned_data_set_source_disable_rank(vtkPartitionedDataSetSource* sself, int rank);
extern "C" void vtk_partitioned_data_set_source_disable_all_ranks(vtkPartitionedDataSetSource* sself);
extern "C" bool vtk_partitioned_data_set_source_is_enabled_rank(vtkPartitionedDataSetSource* sself, int rank);
extern "C" void vtk_partitioned_data_set_source_set_number_of_partitions(vtkPartitionedDataSetSource* sself, int _arg);
extern "C" int vtk_partitioned_data_set_source_get_number_of_partitions_min_value(vtkPartitionedDataSetSource* sself);
extern "C" int vtk_partitioned_data_set_source_get_number_of_partitions_max_value(vtkPartitionedDataSetSource* sself);
extern "C" int vtk_partitioned_data_set_source_get_number_of_partitions(vtkPartitionedDataSetSource* sself);
extern "C" vtkPlaneSource * vtkPlaneSource_new () ;
extern "C" void vtkPlaneSource_destructor (vtkPlaneSource * sself) ;
extern "C" void * vtkPlaneSource_get_ptr (vtkPlaneSource * sself) ;
extern "C" void vtk_plane_source_set_x_resolution(vtkPlaneSource* sself, int _arg);
extern "C" int vtk_plane_source_get_x_resolution(vtkPlaneSource* sself);
extern "C" void vtk_plane_source_set_y_resolution(vtkPlaneSource* sself, int _arg);
extern "C" int vtk_plane_source_get_y_resolution(vtkPlaneSource* sself);
extern "C" void vtk_plane_source_set_resolution(vtkPlaneSource* sself, const int xR, const int yR);
extern "C" void vtk_plane_source_get_resolution(vtkPlaneSource* sself, int& xR, int& yR);
extern "C" void vtk_plane_source_set_origin(vtkPlaneSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_plane_source_set_point_1(vtkPlaneSource* sself, double x, double y, double z);
extern "C" void vtk_plane_source_set_point_2(vtkPlaneSource* sself, double x, double y, double z);
extern "C" void vtk_plane_source_set_center(vtkPlaneSource* sself, double x, double y, double z);
extern "C" void vtk_plane_source_set_normal(vtkPlaneSource* sself, double nx, double ny, double nz);
extern "C" void vtk_plane_source_push(vtkPlaneSource* sself, double distance);
extern "C" void vtk_plane_source_set_output_points_precision(vtkPlaneSource* sself, int _arg);
extern "C" int vtk_plane_source_get_output_points_precision(vtkPlaneSource* sself);
extern "C" vtkPlatonicSolidSource * vtkPlatonicSolidSource_new () ;
extern "C" void vtkPlatonicSolidSource_destructor (vtkPlatonicSolidSource * sself) ;
extern "C" void * vtkPlatonicSolidSource_get_ptr (vtkPlatonicSolidSource * sself) ;
extern "C" void vtk_platonic_solid_source_set_solid_type(vtkPlatonicSolidSource* sself, int _arg);
extern "C" int vtk_platonic_solid_source_get_solid_type_min_value(vtkPlatonicSolidSource* sself);
extern "C" int vtk_platonic_solid_source_get_solid_type_max_value(vtkPlatonicSolidSource* sself);
extern "C" int vtk_platonic_solid_source_get_solid_type(vtkPlatonicSolidSource* sself);
extern "C" void vtk_platonic_solid_source_set_solid_type_to_tetrahedron(vtkPlatonicSolidSource* sself);
extern "C" void vtk_platonic_solid_source_set_solid_type_to_cube(vtkPlatonicSolidSource* sself);
extern "C" void vtk_platonic_solid_source_set_solid_type_to_octahedron(vtkPlatonicSolidSource* sself);
extern "C" void vtk_platonic_solid_source_set_solid_type_to_icosahedron(vtkPlatonicSolidSource* sself);
extern "C" void vtk_platonic_solid_source_set_solid_type_to_dodecahedron(vtkPlatonicSolidSource* sself);
extern "C" void vtk_platonic_solid_source_set_output_points_precision(vtkPlatonicSolidSource* sself, int _arg);
extern "C" int vtk_platonic_solid_source_get_output_points_precision(vtkPlatonicSolidSource* sself);
extern "C" vtkPointHandleSource * vtkPointHandleSource_new () ;
extern "C" void vtkPointHandleSource_destructor (vtkPointHandleSource * sself) ;
extern "C" void * vtkPointHandleSource_get_ptr (vtkPointHandleSource * sself) ;
extern "C" void vtk_point_handle_source_set_position(vtkPointHandleSource* sself, double xPos, double yPos, double zPos);
extern "C" void vtk_point_handle_source_set_direction(vtkPointHandleSource* sself, double xDir, double yDir, double zDir);
extern "C" vtkPointSource * vtkPointSource_new () ;
extern "C" void vtkPointSource_destructor (vtkPointSource * sself) ;
extern "C" void * vtkPointSource_get_ptr (vtkPointSource * sself) ;
extern "C" void vtk_point_source_set_number_of_points(vtkPointSource* sself, long long _arg);
extern "C" long long vtk_point_source_get_number_of_points_min_value(vtkPointSource* sself);
extern "C" long long vtk_point_source_get_number_of_points_max_value(vtkPointSource* sself);
extern "C" long long vtk_point_source_get_number_of_points(vtkPointSource* sself);
extern "C" void vtk_point_source_set_center(vtkPointSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_point_source_set_radius(vtkPointSource* sself, double _arg);
extern "C" double vtk_point_source_get_radius_min_value(vtkPointSource* sself);
extern "C" double vtk_point_source_get_radius_max_value(vtkPointSource* sself);
extern "C" double vtk_point_source_get_radius(vtkPointSource* sself);
extern "C" void vtk_point_source_set_distribution(vtkPointSource* sself, int _arg);
extern "C" void vtk_point_source_set_distribution_to_uniform(vtkPointSource* sself);
extern "C" void vtk_point_source_set_distribution_to_shell(vtkPointSource* sself);
extern "C" int vtk_point_source_get_distribution(vtkPointSource* sself);
extern "C" void vtk_point_source_set_output_points_precision(vtkPointSource* sself, int _arg);
extern "C" int vtk_point_source_get_output_points_precision(vtkPointSource* sself);
extern "C" vtkPolyLineSource * vtkPolyLineSource_new () ;
extern "C" void vtkPolyLineSource_destructor (vtkPolyLineSource * sself) ;
extern "C" void * vtkPolyLineSource_get_ptr (vtkPolyLineSource * sself) ;
extern "C" void vtk_poly_line_source_set_closed(vtkPolyLineSource* sself, int _arg);
extern "C" int vtk_poly_line_source_get_closed(vtkPolyLineSource* sself);
extern "C" void vtk_poly_line_source_closed_on(vtkPolyLineSource* sself);
extern "C" void vtk_poly_line_source_closed_off(vtkPolyLineSource* sself);
extern "C" vtkPolyPointSource * vtkPolyPointSource_new () ;
extern "C" void vtkPolyPointSource_destructor (vtkPolyPointSource * sself) ;
extern "C" void * vtkPolyPointSource_get_ptr (vtkPolyPointSource * sself) ;
extern "C" void vtk_poly_point_source_set_number_of_points(vtkPolyPointSource* sself, long long numPoints);
extern "C" long long vtk_poly_point_source_get_number_of_points(vtkPolyPointSource* sself);
extern "C" void vtk_poly_point_source_resize(vtkPolyPointSource* sself, long long numPoints);
extern "C" void vtk_poly_point_source_set_point(vtkPolyPointSource* sself, long long id, double x, double y, double z);
extern "C" unsigned long vtk_poly_point_source_get_m_time(vtkPolyPointSource* sself);
extern "C" vtkProgrammableDataObjectSource * vtkProgrammableDataObjectSource_new () ;
extern "C" void vtkProgrammableDataObjectSource_destructor (vtkProgrammableDataObjectSource * sself) ;
extern "C" void * vtkProgrammableDataObjectSource_get_ptr (vtkProgrammableDataObjectSource * sself) ;
extern "C" vtkProgrammableSource * vtkProgrammableSource_new () ;
extern "C" void vtkProgrammableSource_destructor (vtkProgrammableSource * sself) ;
extern "C" void * vtkProgrammableSource_get_ptr (vtkProgrammableSource * sself) ;
extern "C" vtkRandomHyperTreeGridSource * vtkRandomHyperTreeGridSource_new () ;
extern "C" void vtkRandomHyperTreeGridSource_destructor (vtkRandomHyperTreeGridSource * sself) ;
extern "C" void * vtkRandomHyperTreeGridSource_get_ptr (vtkRandomHyperTreeGridSource * sself) ;
extern "C" void vtk_random_hyper_tree_grid_source_set_dimensions(vtkRandomHyperTreeGridSource* sself, unsigned int _arg1, unsigned int _arg2, unsigned int _arg3);
extern "C" void vtk_random_hyper_tree_grid_source_set_output_bounds(vtkRandomHyperTreeGridSource* sself, double _arg1, double _arg2, double _arg3, double _arg4, double _arg5, double _arg6);
extern "C" unsigned int vtk_random_hyper_tree_grid_source_get_seed(vtkRandomHyperTreeGridSource* sself);
extern "C" void vtk_random_hyper_tree_grid_source_set_seed(vtkRandomHyperTreeGridSource* sself, unsigned int _arg);
extern "C" long long vtk_random_hyper_tree_grid_source_get_max_depth(vtkRandomHyperTreeGridSource* sself);
extern "C" void vtk_random_hyper_tree_grid_source_set_max_depth(vtkRandomHyperTreeGridSource* sself, long long _arg);
extern "C" long long vtk_random_hyper_tree_grid_source_get_max_depth_min_value(vtkRandomHyperTreeGridSource* sself);
extern "C" long long vtk_random_hyper_tree_grid_source_get_max_depth_max_value(vtkRandomHyperTreeGridSource* sself);
extern "C" double vtk_random_hyper_tree_grid_source_get_split_fraction(vtkRandomHyperTreeGridSource* sself);
extern "C" void vtk_random_hyper_tree_grid_source_set_split_fraction(vtkRandomHyperTreeGridSource* sself, double _arg);
extern "C" double vtk_random_hyper_tree_grid_source_get_split_fraction_min_value(vtkRandomHyperTreeGridSource* sself);
extern "C" double vtk_random_hyper_tree_grid_source_get_split_fraction_max_value(vtkRandomHyperTreeGridSource* sself);
extern "C" vtkRectangularButtonSource * vtkRectangularButtonSource_new () ;
extern "C" void vtkRectangularButtonSource_destructor (vtkRectangularButtonSource * sself) ;
extern "C" void * vtkRectangularButtonSource_get_ptr (vtkRectangularButtonSource * sself) ;
extern "C" void vtk_rectangular_button_source_set_width(vtkRectangularButtonSource* sself, double _arg);
extern "C" double vtk_rectangular_button_source_get_width_min_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_width_max_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_width(vtkRectangularButtonSource* sself);
extern "C" void vtk_rectangular_button_source_set_height(vtkRectangularButtonSource* sself, double _arg);
extern "C" double vtk_rectangular_button_source_get_height_min_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_height_max_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_height(vtkRectangularButtonSource* sself);
extern "C" void vtk_rectangular_button_source_set_depth(vtkRectangularButtonSource* sself, double _arg);
extern "C" double vtk_rectangular_button_source_get_depth_min_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_depth_max_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_depth(vtkRectangularButtonSource* sself);
extern "C" void vtk_rectangular_button_source_set_box_ratio(vtkRectangularButtonSource* sself, double _arg);
extern "C" double vtk_rectangular_button_source_get_box_ratio_min_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_box_ratio_max_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_box_ratio(vtkRectangularButtonSource* sself);
extern "C" void vtk_rectangular_button_source_set_texture_ratio(vtkRectangularButtonSource* sself, double _arg);
extern "C" double vtk_rectangular_button_source_get_texture_ratio_min_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_texture_ratio_max_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_texture_ratio(vtkRectangularButtonSource* sself);
extern "C" void vtk_rectangular_button_source_set_texture_height_ratio(vtkRectangularButtonSource* sself, double _arg);
extern "C" double vtk_rectangular_button_source_get_texture_height_ratio_min_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_texture_height_ratio_max_value(vtkRectangularButtonSource* sself);
extern "C" double vtk_rectangular_button_source_get_texture_height_ratio(vtkRectangularButtonSource* sself);
extern "C" void vtk_rectangular_button_source_set_output_points_precision(vtkRectangularButtonSource* sself, int _arg);
extern "C" int vtk_rectangular_button_source_get_output_points_precision(vtkRectangularButtonSource* sself);
extern "C" vtkRegularPolygonSource * vtkRegularPolygonSource_new () ;
extern "C" void vtkRegularPolygonSource_destructor (vtkRegularPolygonSource * sself) ;
extern "C" void * vtkRegularPolygonSource_get_ptr (vtkRegularPolygonSource * sself) ;
extern "C" void vtk_regular_polygon_source_set_number_of_sides(vtkRegularPolygonSource* sself, int _arg);
extern "C" int vtk_regular_polygon_source_get_number_of_sides_min_value(vtkRegularPolygonSource* sself);
extern "C" int vtk_regular_polygon_source_get_number_of_sides_max_value(vtkRegularPolygonSource* sself);
extern "C" int vtk_regular_polygon_source_get_number_of_sides(vtkRegularPolygonSource* sself);
extern "C" void vtk_regular_polygon_source_set_center(vtkRegularPolygonSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_regular_polygon_source_set_normal(vtkRegularPolygonSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_regular_polygon_source_set_radius(vtkRegularPolygonSource* sself, double _arg);
extern "C" double vtk_regular_polygon_source_get_radius(vtkRegularPolygonSource* sself);
extern "C" void vtk_regular_polygon_source_set_generate_polygon(vtkRegularPolygonSource* sself, int _arg);
extern "C" int vtk_regular_polygon_source_get_generate_polygon(vtkRegularPolygonSource* sself);
extern "C" void vtk_regular_polygon_source_generate_polygon_on(vtkRegularPolygonSource* sself);
extern "C" void vtk_regular_polygon_source_generate_polygon_off(vtkRegularPolygonSource* sself);
extern "C" void vtk_regular_polygon_source_set_generate_polyline(vtkRegularPolygonSource* sself, int _arg);
extern "C" int vtk_regular_polygon_source_get_generate_polyline(vtkRegularPolygonSource* sself);
extern "C" void vtk_regular_polygon_source_generate_polyline_on(vtkRegularPolygonSource* sself);
extern "C" void vtk_regular_polygon_source_generate_polyline_off(vtkRegularPolygonSource* sself);
extern "C" void vtk_regular_polygon_source_set_output_points_precision(vtkRegularPolygonSource* sself, int _arg);
extern "C" int vtk_regular_polygon_source_get_output_points_precision(vtkRegularPolygonSource* sself);
extern "C" vtkSelectionSource * vtkSelectionSource_new () ;
extern "C" void vtkSelectionSource_destructor (vtkSelectionSource * sself) ;
extern "C" void * vtkSelectionSource_get_ptr (vtkSelectionSource * sself) ;
extern "C" void vtk_selection_source_add_id(vtkSelectionSource* sself, long long piece, long long id);
extern "C" void vtk_selection_source_add_string_id(vtkSelectionSource* sself, long long piece, const char* id);
extern "C" void vtk_selection_source_add_location(vtkSelectionSource* sself, double x, double y, double z);
extern "C" void vtk_selection_source_add_threshold(vtkSelectionSource* sself, double min, double max);
extern "C" void vtk_selection_source_add_block(vtkSelectionSource* sself, long long blockno);
extern "C" void vtk_selection_source_add_block_selector(vtkSelectionSource* sself, const char* selector);
extern "C" void vtk_selection_source_remove_all_block_selectors(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_remove_all_i_ds(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_remove_all_string_i_ds(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_remove_all_thresholds(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_remove_all_locations(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_remove_all_blocks(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_set_content_type(vtkSelectionSource* sself, int _arg);
extern "C" int vtk_selection_source_get_content_type(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_set_field_type(vtkSelectionSource* sself, int _arg);
extern "C" int vtk_selection_source_get_field_type(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_set_containing_cells(vtkSelectionSource* sself, int _arg);
extern "C" int vtk_selection_source_get_containing_cells(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_set_number_of_layers(vtkSelectionSource* sself, int _arg);
extern "C" int vtk_selection_source_get_number_of_layers_min_value(vtkSelectionSource* sself);
extern "C" int vtk_selection_source_get_number_of_layers_max_value(vtkSelectionSource* sself);
extern "C" int vtk_selection_source_get_number_of_layers(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_set_inverse(vtkSelectionSource* sself, int _arg);
extern "C" int vtk_selection_source_get_inverse(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_set_array_name(vtkSelectionSource* sself, const char* _arg);
extern "C" void vtk_selection_source_set_array_component(vtkSelectionSource* sself, int _arg);
extern "C" int vtk_selection_source_get_array_component(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_set_composite_index(vtkSelectionSource* sself, int _arg);
extern "C" int vtk_selection_source_get_composite_index(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_set_hierarchical_level(vtkSelectionSource* sself, int _arg);
extern "C" int vtk_selection_source_get_hierarchical_level(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_set_hierarchical_index(vtkSelectionSource* sself, int _arg);
extern "C" int vtk_selection_source_get_hierarchical_index(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_set_assembly_name(vtkSelectionSource* sself, const char* _arg);
extern "C" void vtk_selection_source_add_selector(vtkSelectionSource* sself, const char* selector);
extern "C" void vtk_selection_source_remove_all_selectors(vtkSelectionSource* sself);
extern "C" void vtk_selection_source_set_query_string(vtkSelectionSource* sself, const char* _arg);
extern "C" vtkSphereSource * vtkSphereSource_new () ;
extern "C" void vtkSphereSource_destructor (vtkSphereSource * sself) ;
extern "C" void * vtkSphereSource_get_ptr (vtkSphereSource * sself) ;
extern "C" void vtk_sphere_source_set_radius(vtkSphereSource* sself, double _arg);
extern "C" double vtk_sphere_source_get_radius_min_value(vtkSphereSource* sself);
extern "C" double vtk_sphere_source_get_radius_max_value(vtkSphereSource* sself);
extern "C" double vtk_sphere_source_get_radius(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_set_center(vtkSphereSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_sphere_source_set_theta_resolution(vtkSphereSource* sself, int _arg);
extern "C" int vtk_sphere_source_get_theta_resolution_min_value(vtkSphereSource* sself);
extern "C" int vtk_sphere_source_get_theta_resolution_max_value(vtkSphereSource* sself);
extern "C" int vtk_sphere_source_get_theta_resolution(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_set_phi_resolution(vtkSphereSource* sself, int _arg);
extern "C" int vtk_sphere_source_get_phi_resolution_min_value(vtkSphereSource* sself);
extern "C" int vtk_sphere_source_get_phi_resolution_max_value(vtkSphereSource* sself);
extern "C" int vtk_sphere_source_get_phi_resolution(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_set_start_theta(vtkSphereSource* sself, double _arg);
extern "C" double vtk_sphere_source_get_start_theta_min_value(vtkSphereSource* sself);
extern "C" double vtk_sphere_source_get_start_theta_max_value(vtkSphereSource* sself);
extern "C" double vtk_sphere_source_get_start_theta(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_set_end_theta(vtkSphereSource* sself, double _arg);
extern "C" double vtk_sphere_source_get_end_theta_min_value(vtkSphereSource* sself);
extern "C" double vtk_sphere_source_get_end_theta_max_value(vtkSphereSource* sself);
extern "C" double vtk_sphere_source_get_end_theta(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_set_start_phi(vtkSphereSource* sself, double _arg);
extern "C" double vtk_sphere_source_get_start_phi_min_value(vtkSphereSource* sself);
extern "C" double vtk_sphere_source_get_start_phi_max_value(vtkSphereSource* sself);
extern "C" double vtk_sphere_source_get_start_phi(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_set_end_phi(vtkSphereSource* sself, double _arg);
extern "C" double vtk_sphere_source_get_end_phi_min_value(vtkSphereSource* sself);
extern "C" double vtk_sphere_source_get_end_phi_max_value(vtkSphereSource* sself);
extern "C" double vtk_sphere_source_get_end_phi(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_set_lat_long_tessellation(vtkSphereSource* sself, int _arg);
extern "C" int vtk_sphere_source_get_lat_long_tessellation(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_lat_long_tessellation_on(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_lat_long_tessellation_off(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_set_output_points_precision(vtkSphereSource* sself, int _arg);
extern "C" int vtk_sphere_source_get_output_points_precision(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_set_generate_normals(vtkSphereSource* sself, int _arg);
extern "C" int vtk_sphere_source_get_generate_normals(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_generate_normals_on(vtkSphereSource* sself);
extern "C" void vtk_sphere_source_generate_normals_off(vtkSphereSource* sself);
extern "C" vtkSuperquadricSource * vtkSuperquadricSource_new () ;
extern "C" void vtkSuperquadricSource_destructor (vtkSuperquadricSource * sself) ;
extern "C" void * vtkSuperquadricSource_get_ptr (vtkSuperquadricSource * sself) ;
extern "C" void vtk_superquadric_source_set_center(vtkSuperquadricSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_superquadric_source_set_scale(vtkSuperquadricSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" int vtk_superquadric_source_get_theta_resolution(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_set_theta_resolution(vtkSuperquadricSource* sself, int i);
extern "C" int vtk_superquadric_source_get_phi_resolution(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_set_phi_resolution(vtkSuperquadricSource* sself, int i);
extern "C" double vtk_superquadric_source_get_thickness(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_set_thickness(vtkSuperquadricSource* sself, double _arg);
extern "C" double vtk_superquadric_source_get_thickness_min_value(vtkSuperquadricSource* sself);
extern "C" double vtk_superquadric_source_get_thickness_max_value(vtkSuperquadricSource* sself);
extern "C" double vtk_superquadric_source_get_phi_roundness(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_set_phi_roundness(vtkSuperquadricSource* sself, double e);
extern "C" double vtk_superquadric_source_get_theta_roundness(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_set_theta_roundness(vtkSuperquadricSource* sself, double e);
extern "C" void vtk_superquadric_source_set_size(vtkSuperquadricSource* sself, double _arg);
extern "C" double vtk_superquadric_source_get_size(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_set_axis_of_symmetry(vtkSuperquadricSource* sself, int _arg);
extern "C" int vtk_superquadric_source_get_axis_of_symmetry(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_set_x_axis_of_symmetry(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_set_y_axis_of_symmetry(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_set_z_axis_of_symmetry(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_toroidal_on(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_toroidal_off(vtkSuperquadricSource* sself);
extern "C" int vtk_superquadric_source_get_toroidal(vtkSuperquadricSource* sself);
extern "C" void vtk_superquadric_source_set_toroidal(vtkSuperquadricSource* sself, int _arg);
extern "C" void vtk_superquadric_source_set_output_points_precision(vtkSuperquadricSource* sself, int _arg);
extern "C" int vtk_superquadric_source_get_output_points_precision(vtkSuperquadricSource* sself);
extern "C" vtkTessellatedBoxSource * vtkTessellatedBoxSource_new () ;
extern "C" void vtkTessellatedBoxSource_destructor (vtkTessellatedBoxSource * sself) ;
extern "C" void * vtkTessellatedBoxSource_get_ptr (vtkTessellatedBoxSource * sself) ;
extern "C" void vtk_tessellated_box_source_set_bounds(vtkTessellatedBoxSource* sself, double _arg1, double _arg2, double _arg3, double _arg4, double _arg5, double _arg6);
extern "C" void vtk_tessellated_box_source_set_level(vtkTessellatedBoxSource* sself, int _arg);
extern "C" int vtk_tessellated_box_source_get_level(vtkTessellatedBoxSource* sself);
extern "C" void vtk_tessellated_box_source_set_duplicate_shared_points(vtkTessellatedBoxSource* sself, int _arg);
extern "C" int vtk_tessellated_box_source_get_duplicate_shared_points(vtkTessellatedBoxSource* sself);
extern "C" void vtk_tessellated_box_source_duplicate_shared_points_on(vtkTessellatedBoxSource* sself);
extern "C" void vtk_tessellated_box_source_duplicate_shared_points_off(vtkTessellatedBoxSource* sself);
extern "C" void vtk_tessellated_box_source_set_quads(vtkTessellatedBoxSource* sself, int _arg);
extern "C" int vtk_tessellated_box_source_get_quads(vtkTessellatedBoxSource* sself);
extern "C" void vtk_tessellated_box_source_quads_on(vtkTessellatedBoxSource* sself);
extern "C" void vtk_tessellated_box_source_quads_off(vtkTessellatedBoxSource* sself);
extern "C" void vtk_tessellated_box_source_set_output_points_precision(vtkTessellatedBoxSource* sself, int _arg);
extern "C" int vtk_tessellated_box_source_get_output_points_precision(vtkTessellatedBoxSource* sself);
extern "C" vtkTextSource * vtkTextSource_new () ;
extern "C" void vtkTextSource_destructor (vtkTextSource * sself) ;
extern "C" void * vtkTextSource_get_ptr (vtkTextSource * sself) ;
extern "C" void vtk_text_source_set_text(vtkTextSource* sself, const char* _arg);
extern "C" void vtk_text_source_set_backing(vtkTextSource* sself, int _arg);
extern "C" int vtk_text_source_get_backing(vtkTextSource* sself);
extern "C" void vtk_text_source_backing_on(vtkTextSource* sself);
extern "C" void vtk_text_source_backing_off(vtkTextSource* sself);
extern "C" void vtk_text_source_set_foreground_color(vtkTextSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_text_source_set_background_color(vtkTextSource* sself, double _arg1, double _arg2, double _arg3);
extern "C" void vtk_text_source_set_output_points_precision(vtkTextSource* sself, int _arg);
extern "C" int vtk_text_source_get_output_points_precision(vtkTextSource* sself);
extern "C" vtkTexturedSphereSource * vtkTexturedSphereSource_new () ;
extern "C" void vtkTexturedSphereSource_destructor (vtkTexturedSphereSource * sself) ;
extern "C" void * vtkTexturedSphereSource_get_ptr (vtkTexturedSphereSource * sself) ;
extern "C" void vtk_textured_sphere_source_set_radius(vtkTexturedSphereSource* sself, double _arg);
extern "C" double vtk_textured_sphere_source_get_radius_min_value(vtkTexturedSphereSource* sself);
extern "C" double vtk_textured_sphere_source_get_radius_max_value(vtkTexturedSphereSource* sself);
extern "C" double vtk_textured_sphere_source_get_radius(vtkTexturedSphereSource* sself);
extern "C" void vtk_textured_sphere_source_set_theta_resolution(vtkTexturedSphereSource* sself, int _arg);
extern "C" int vtk_textured_sphere_source_get_theta_resolution_min_value(vtkTexturedSphereSource* sself);
extern "C" int vtk_textured_sphere_source_get_theta_resolution_max_value(vtkTexturedSphereSource* sself);
extern "C" int vtk_textured_sphere_source_get_theta_resolution(vtkTexturedSphereSource* sself);
extern "C" void vtk_textured_sphere_source_set_phi_resolution(vtkTexturedSphereSource* sself, int _arg);
extern "C" int vtk_textured_sphere_source_get_phi_resolution_min_value(vtkTexturedSphereSource* sself);
extern "C" int vtk_textured_sphere_source_get_phi_resolution_max_value(vtkTexturedSphereSource* sself);
extern "C" int vtk_textured_sphere_source_get_phi_resolution(vtkTexturedSphereSource* sself);
extern "C" void vtk_textured_sphere_source_set_theta(vtkTexturedSphereSource* sself, double _arg);
extern "C" double vtk_textured_sphere_source_get_theta_min_value(vtkTexturedSphereSource* sself);
extern "C" double vtk_textured_sphere_source_get_theta_max_value(vtkTexturedSphereSource* sself);
extern "C" double vtk_textured_sphere_source_get_theta(vtkTexturedSphereSource* sself);
extern "C" void vtk_textured_sphere_source_set_phi(vtkTexturedSphereSource* sself, double _arg);
extern "C" double vtk_textured_sphere_source_get_phi_min_value(vtkTexturedSphereSource* sself);
extern "C" double vtk_textured_sphere_source_get_phi_max_value(vtkTexturedSphereSource* sself);
extern "C" double vtk_textured_sphere_source_get_phi(vtkTexturedSphereSource* sself);
extern "C" void vtk_textured_sphere_source_set_output_points_precision(vtkTexturedSphereSource* sself, int _arg);
extern "C" int vtk_textured_sphere_source_get_output_points_precision(vtkTexturedSphereSource* sself);
extern "C" vtkUniformHyperTreeGridSource * vtkUniformHyperTreeGridSource_new () ;
extern "C" void vtkUniformHyperTreeGridSource_destructor (vtkUniformHyperTreeGridSource * sself) ;
extern "C" void * vtkUniformHyperTreeGridSource_get_ptr (vtkUniformHyperTreeGridSource * sself) ;
